<?php
function weirdWords($filename){
    $words_following_rules = array();
    $words_not_following_rules = array();

    try{
        $file = fopen($filename, "r");

        # get the contents from the file
        $content = file_get_contents($filename);

        # replace every non alphanumeric character with a space
        $content = preg_replace("/[^A-Za-z0-9 \n]/", ' ', $content);
        # split the words using the space as separator
        $split_words = preg_split("/\s+/", $content,-1,PREG_SPLIT_NO_EMPTY);
        fclose($file);

        # loop the array generated by splitting the words
        foreach($split_words as $word){
            $w = strtolower($word);
            
            # if the word respect the rules insert them into the array
            if ((str_contains($w, 'ie')) || (str_contains($w, 'cei'))){
                if (!in_array($w, $words_following_rules)){
                    array_push($words_following_rules, $w);
                }
            }
            else{
                if (!in_array($w, $words_not_following_rules)){
                    array_push($words_not_following_rules, $w);
                }
            }
        }    
        
        #return $words_following_rules;
        return array($words_following_rules,$words_not_following_rules);
        
    }
    catch (Exception $e){
        echo "Error ".$e;
    }
}

var_dump(weirdWords("../../utils/emma.txt"));
?>