<?php
function randomPassword($filename){
    $words = array();

    try{
        $file = fopen($filename, "r");

        # get the contents from the file
        $content = file_get_contents($filename);

        # split the words using the space as separator, and delete every non alphanumeric character
        $split_words = preg_split('/\s+/',(preg_replace("/[^A-Za-z0-9 ]/", '', $content)),-1,PREG_SPLIT_NO_EMPTY);
        fclose($file);

        # loop the array generated by splitting the words
        foreach($split_words as $word){
            $w = strtolower($word);

            # insert the unique words longer than or equal to 3 charecters
            if (!in_array($w, $words) && (strlen($w) >= 3)){
                array_push($words, $w);
            }
        }    
        
        
        $check = TRUE;
        while ($check == TRUE){
            # get 2 random words from the array
            $rand_keys = array_rand($words, 2);
            
            # if the 2 random words are equal or longer than 8
            # and together are no longer than 10
            # create the password with the 2 words with first capital letter
            if ((strlen($words[$rand_keys[0]].$words[$rand_keys[1]]) >= 8) && (strlen($words[$rand_keys[0]].$words[$rand_keys[1]]) <= 10)){
                $password = ucfirst($words[$rand_keys[0]]).ucfirst($words[$rand_keys[1]]);
                $check = FALSE;
            }
        }
        
        return $password;
        
    }
    catch (Exception $e){
        echo "Error ".$e;
    }
}

echo randomPassword("../../utils/sample_file.txt");
?>